{% set name = "auxeticmop" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b83f1ab6ab311131f7c31699de59f3bff484c49b9dc9186ced0d03a2a97e08b4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - aiofiles
    - matplotlib
    - numba
    - numpy
    - pip
    - python
    - scipy
  run:
    - aiofiles
    - matplotlib
    - numba
    - numpy
    - python
    - scipy

test:
  imports:
    - auxeticmop
    - auxeticmop.sample_scripts

about:
  home: "https://github.com/c0sogi/AuxeticMOP-with-ABAQUS"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A package for finding meta-material structure using ABAQUS and MOP evolutionary algorithm approaches."
  doc_url: 
  dev_url:

extra:
  recipe-maintainers:
    - c0sogi