{% set name = "auxeticmop" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/c0sogi/auxeticmop.git
  git_rev: v1.0.2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - aiofiles
    - matplotlib
    - numba
    - numpy
    - pip
    - python
    - scipy
    - dataclasses
  run:
    - aiofiles
    - matplotlib
    - numba
    - numpy
    - python
    - scipy
    - dataclasses

test:
  imports:
    - auxeticmop
    - auxeticmop.sample_scripts

about:
  home: "https://github.com/c0sogi/AuxeticMOP-with-ABAQUS"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A package for finding meta-material structure using ABAQUS and MOP evolutionary algorithm approaches."
  doc_url: 
  dev_url:

extra:
  recipe-maintainers:
    - c0sogi